import React, { createContext, useContext, useState, useEffect } from 'react';
import { DATA_TRANSLATIONS } from './DataTranslations';

export type LanguageCode = 'EN' | 'ES' | 'FR' | 'HI' | 'AR' | 'DE' | 'JA' | 'ZH' | 'RU' | 'PT' | 'IT' | 'TR';

interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'EN', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ES', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'FR', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'HI', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'AR', name: 'Arabic', nativeName: 'العربية', flag: '🇦🇪' },
  { code: 'DE', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'JA', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ZH', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'RU', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'PT', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'IT', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'TR', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' }
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  EN: {
    'Dashboard': 'Dashboard',
    'Doctors': 'Doctors',
    'Patients': 'Patients',
    'Appointments': 'Appointments',
    'Lab Reports': 'Lab Reports',
    'Pharmacy': 'Pharmacy',
    'Billing': 'Billing',
    'Staff & HR': 'Staff & HR',
    'Inventory': 'Inventory',
    'Ambulance': 'Ambulance',
    'Communication': 'Communication',
    'Birthday System': 'Birthday System',
    'Reports': 'Reports',
    'AI Assistant': 'AI Assistant',
    'Notifications': 'Notifications',
    'Roles & Permissions': 'Roles & Permissions',
    'Settings': 'Settings',
    'Profile': 'Profile',
    'Logout': 'Logout',
    'Admin Dashboard': 'Admin Dashboard',
    'Today\'s Celebrants Widget': 'Today\'s Celebrants Widget',
    'OS Operational Branches': 'OS Operational Branches',
    'Add New Operating Branch': 'Add New Operating Branch',
    'Ask AI, search patients, audit logs...': 'Ask AI, search patients, audit logs...',
    'EMERGENCY': 'EMERGENCY',
    'SLA BREACH ACTIVE': 'SLA BREACH ACTIVE',
    'SYSTEM IN LOCKDOWN': 'SYSTEM IN LOCKDOWN',
    'Communications': 'Communications',
    'Clear All': 'Clear All',
    'System Nominal': 'System Nominal',
    'Profile Options': 'Profile Options',
    'System Prefs': 'System Prefs',
    'Log Out': 'Log Out',
    'Hospital Details': 'Hospital Details',
    'Admin': 'Admin',
    'Today\'s Clinical Events': 'Today\'s Clinical Events',
    'Active Patients': 'Active Patients',
    'Doctors Engaged': 'Doctors Engaged',
    'Scheduled Consults': 'Scheduled Consults',
    'Pending Lab Assays': 'Pending Lab Assays',
    'Total Revenue': 'Total Revenue',
    'System Active Broadcasts': 'System Active Broadcasts',
    'Language Selected': 'Language Selected',
    'Enter Branch...': 'ENTER BRANCH...',
    'Add': 'Add',
    'Active Admissions': 'Active Admissions',
    'Today\'s Clinical Special Events': 'Today\'s Clinical Special Events',
    'Action Required': 'Action Required',
    'Configure System-wide details': 'Configure System-wide details',
    'Registered Personnel': 'Registered Personnel',
    'Quick Access': 'Quick Access',
    'Hospital HQ': 'Hospital HQ'
  },
  ES: {
    'Dashboard': 'Controles',
    'Doctors': 'Médicos',
    'Patients': 'Pacientes',
    'Appointments': 'Citas',
    'Lab Reports': 'Informes del Lab',
    'Pharmacy': 'Farmacia',
    'Billing': 'Facturación',
    'Staff & HR': 'Personal y RRHH',
    'Inventory': 'Inventario',
    'Ambulance': 'Ambulancia',
    'Communication': 'Comunicación',
    'Birthday System': 'Sistema Cumpleaños',
    'Reports': 'Informes',
    'AI Assistant': 'Asistente de IA',
    'Notifications': 'Notificaciones',
    'Roles & Permissions': 'Roles y Permisos',
    'Settings': 'Configuración',
    'Profile': 'Perfil',
    'Logout': 'Cerrar Sesión',
    'Admin Dashboard': 'Panel de Admin',
    'Today\'s Celebrants Widget': 'Cupón de Celebraciones',
    'OS Operational Branches': 'Filiales Operativas',
    'Add New Operating Branch': 'Añadir Nueva Sucursal',
    'Ask AI, search patients, audit logs...': 'Pregunta a IA, buscar pacientes...',
    'EMERGENCY': 'EMERGENCIA',
    'SLA BREACH ACTIVE': 'INCUMPLIMIENTO DE SLA',
    'SYSTEM IN LOCKDOWN': 'SISTEMA BLOQUEADO',
    'Communications': 'Comunicaciones',
    'Clear All': 'Limpiar Todo',
    'System Nominal': 'Sistema Nominal',
    'Profile Options': 'Opciones del Perfil',
    'System Prefs': 'Preferencias',
    'Log Out': 'Cerrar Sesión',
    'Hospital Details': 'Detalles del Hospital',
    'Admin': 'Administrador',
    'Today\'s Clinical Events': 'Eventos Clínicos de Hoy',
    'Active Patients': 'Pacientes Activos',
    'Doctors Engaged': 'Médicos Compometidos',
    'Scheduled Consults': 'Consultas Programadas',
    'Pending Lab Assays': 'Analíticas Pendientes',
    'Total Revenue': 'Ingresos Totales',
    'System Active Broadcasts': 'Mensajes Activos',
    'Language Selected': 'Idioma Elegido',
    'Enter Branch...': 'SUCURSAL DE ENTRADA...',
    'Add': 'Añadir',
    'Active Admissions': 'Admisiones Activas',
    'Today\'s Clinical Special Events': 'Eventos Especiales de Hoy',
    'Action Required': 'Acción Necesaria',
    'Configure System-wide details': 'Configuración General del Sistema',
    'Registered Personnel': 'Personal Registrado',
    'Quick Access': 'Acceso Rápido',
    'Hospital HQ': 'HQ Principal'
  },
  FR: {
    'Dashboard': 'Tableau de bord',
    'Doctors': 'Médecins',
    'Patients': 'Patients',
    'Appointments': 'Rendez-vous',
    'Lab Reports': 'Labo & Analyses',
    'Pharmacy': 'Pharmacie',
    'Billing': 'Facturation',
    'Staff & HR': 'Personnel & RH',
    'Inventory': 'Inventaire',
    'Ambulance': 'Ambulance',
    'Communication': 'Communication',
    'Birthday System': 'Anniversaires',
    'Reports': 'Compte-rendu',
    'AI Assistant': 'Assistant IA',
    'Notifications': 'Notifications',
    'Roles & Permissions': 'Rôles & Accès',
    'Settings': 'Paramètres',
    'Profile': 'Mon Profil',
    'Logout': 'Déconnexion',
    'Admin Dashboard': 'Console Admin',
    'Today\'s Celebrants Widget': 'Widget Anniversaires',
    'OS Operational Branches': 'Succursales Actives',
    'Add New Operating Branch': 'Ajouter une Succursale',
    'Ask AI, search patients, audit logs...': 'Rechercher des patients, logs, IA...',
    'EMERGENCY': 'URGENCE',
    'SLA BREACH ACTIVE': 'RUPTURE DE SLA ACTIVE',
    'SYSTEM IN LOCKDOWN': 'SYS EN CONFINEMENT',
    'Communications': 'Communications',
    'Clear All': 'Tout Effacer',
    'System Nominal': 'Système Nominal',
    'Profile Options': 'Options de Profil',
    'System Prefs': 'Ajustement Système',
    'Log Out': 'Déconnexion',
    'Hospital Details': 'Détails de l\'Hôpital',
    'Admin': 'Admin',
    'Today\'s Clinical Events': 'Événements Cliniques',
    'Active Patients': 'Patients Actifs',
    'Doctors Engaged': 'Médecins Actifs',
    'Scheduled Consults': 'Consultations Prévues',
    'Pending Lab Assays': 'Analyses en Cours',
    'Total Revenue': 'Revenu Global',
    'System Active Broadcasts': 'Alertes Diffusées',
    'Language Selected': 'Langue Sélectionnée',
    'Enter Branch...': 'Saisir Succursale...',
    'Add': 'Ajouter',
    'Active Admissions': 'Admissions Actives',
    'Today\'s Clinical Special Events': 'Célébrations d\'Aujourd\'hui',
    'Action Required': 'Action Requise',
    'Configure System-wide details': 'Détails de l\'Infrastructure',
    'Registered Personnel': 'Personnel Inscrit',
    'Quick Access': 'Raccourcis',
    'Hospital HQ': 'HQ Hôpital'
  },
  HI: {
    'Dashboard': 'डैशबोर्ड',
    'Doctors': 'चिकित्सक',
    'Patients': 'रोगी',
    'Appointments': 'नियत समय',
    'Lab Reports': 'लैब रिपोर्ट',
    'Pharmacy': 'औषधालय',
    'Billing': 'बिलिंग',
    'Staff & HR': 'स्टाफ और एचआर',
    'Inventory': 'इन्वेंटरी',
    'Ambulance': 'एम्बुलेंस',
    'Communication': 'संचार सेवा',
    'Birthday System': 'जन्मदिन प्रणाली',
    'Reports': 'रिपोर्ट एवं डेटा',
    'AI Assistant': 'एआई सहायक',
    'Notifications': 'अधिसूचनाएं',
    'Roles & Permissions': 'भूमिकाएं और अनुमतियां',
    'Settings': 'सेटिंग्स',
    'Profile': 'प्रोफ़ाइल',
    'Logout': 'लॉग आउट',
    'Admin Dashboard': 'एडमिन डैशबोर्ड',
    'Today\'s Celebrants Widget': 'आज के जन्मदिन',
    'OS Operational Branches': 'संचालन शाखाएं',
    'Add New Operating Branch': 'नई शाखा जोड़ें',
    'Ask AI, search patients, audit logs...': 'एआई से पूछें, मरीज खोजें...',
    'EMERGENCY': 'आपातकाल',
    'SLA BREACH ACTIVE': 'SLA उल्लंघन सक्रिय',
    'SYSTEM IN LOCKDOWN': 'सिस्टम लॉकडाउन',
    'Communications': 'संचार संदेश',
    'Clear All': 'सब हटाएँ',
    'System Nominal': 'सिस्टम सुरक्षित है',
    'Profile Options': 'प्रोफ़ाइल विकल्प',
    'System Prefs': 'सिस्टम वरीयताएँ',
    'Log Out': 'लॉग आउट',
    'Hospital Details': 'अस्पताल विवरण',
    'Admin': 'प्रशासक',
    'Today\'s Clinical Events': 'आज के क्लिनिकल कार्यक्रम',
    'Active Patients': 'सक्रिय मरीज़',
    'Doctors Engaged': 'सक्रिय डॉक्टर',
    'Scheduled Consults': 'निर्धारित परामर्श',
    'Pending Lab Assays': 'लंबित लैब परीक्षण',
    'Total Revenue': 'कुल राजस्व',
    'System Active Broadcasts': 'सक्रिय प्रसारण',
    'Language Selected': 'भाषा का चयन हुआ',
    'Enter Branch...': 'शाखा का नाम...',
    'Add': 'जोड़ें',
    'Active Admissions': 'सक्रिय भर्ती',
    'Today\'s Clinical Special Events': 'आज के विशेष कार्यक्रम',
    'Action Required': 'कार्रवाई आवश्यक',
    'Configure System-wide details': 'सिस्टम-व्यापी विवरण कॉन्फ़िगर करें',
    'Registered Personnel': 'पंजीकृत कर्मी',
    'Quick Access': 'त्वरित पहुँच',
    'Hospital HQ': 'अस्पताल मुख्यालय'
  },
  AR: {
    'Dashboard': 'لوحة القيادة',
    'Doctors': 'الأطباء',
    'Patients': 'المرضى',
    'Appointments': 'المواعيد',
    'Lab Reports': 'تقارير المختبر',
    'Pharmacy': 'الصيدلية',
    'Billing': 'الفواتير والمالية',
    'Staff & HR': 'الموظفين والموارد',
    'Inventory': 'المخزون والسلع',
    'Ambulance': 'خدمة الإسعاف',
    'Communication': 'الاتصالات',
    'Birthday System': 'أعياد الميلاد',
    'Reports': 'التقارير الطبية',
    'AI Assistant': 'المساعد الذكي',
    'Notifications': 'الإشعارات',
    'Roles & Permissions': 'الأدوار والصلاحيات',
    'Settings': 'إعدادات النظام',
    'Profile': 'الملف الشخصي',
    'Logout': 'تسجيل الخروج',
    'Admin Dashboard': 'لوحة تحكم المشرف',
    'Today\'s Celebrants Widget': 'أعياد ميلاد اليوم',
    'OS Operational Branches': 'فروع التشغيل',
    'Add New Operating Branch': 'إضافة فرع تشغيل جديد',
    'Ask AI, search patients, audit logs...': 'اسأل الذكاء الاصطناعي، ابحث...',
    'EMERGENCY': 'حالة طوارئ',
    'SLA BREACH ACTIVE': 'خرق معايير الخدمة نشط',
    'SYSTEM IN LOCKDOWN': 'نظام مغلق ومؤمن',
    'Communications': 'الاتصالات الواردة',
    'Clear All': 'مسح الكل',
    'System Nominal': 'النظام مستقر',
    'Profile Options': 'خيارات الملف',
    'System Prefs': 'تفضيلات التشغيل',
    'Log Out': 'تسجيل خروج',
    'Hospital Details': 'بيانات المستشفى',
    'Admin': 'المشرف المسؤول',
    'Today\'s Clinical Events': 'فعاليات اليوم الطبية',
    'Active Patients': 'المرضى الفاعلين',
    'Doctors Engaged': 'الأطباء المناوبين',
    'Scheduled Consults': 'الاستشارات المجدولة',
    'Pending Lab Assays': 'فحوصات معلقة',
    'Total Revenue': 'إجمالي الإيرادات',
    'System Active Broadcasts': 'البرقيات النشطة',
    'Language Selected': 'تم تغيير اللغة إلى العربية',
    'Enter Branch...': 'أدخل اسم الفرع...',
    'Add': 'إضافة',
    'Active Admissions': 'حالات الدخول النشطة',
    'Today\'s Clinical Special Events': 'مهرجانات خاصة اليوم',
    'Action Required': 'مطلوب إجراء فوري',
    'Configure System-wide details': 'إعدادات المنشأة الشاملة',
    'Registered Personnel': 'الكوادر المسجلة',
    'Quick Access': 'دخول سريع',
    'Hospital HQ': 'المقر الرئيسي'
  },
  DE: {
    'Dashboard': 'Cockpit',
    'Doctors': 'Ärzte',
    'Patients': 'Patienten',
    'Appointments': 'Konsultationen',
    'Lab Reports': 'Laborberichte',
    'Pharmacy': 'Apotheke',
    'Billing': 'Abrechnung',
    'Staff & HR': 'Mitarbeiter & HR',
    'Inventory': 'Lagerverwaltung',
    'Ambulance': 'Rettungsdienst',
    'Communication': 'Kommunikation',
    'Birthday System': 'Anlässe',
    'Reports': 'Berichte',
    'AI Assistant': 'KI-Assistent',
    'Notifications': 'Meldungen',
    'Roles & Permissions': 'Rollen & Rechte',
    'Settings': 'Systemoptionen',
    'Profile': 'Mein Profil',
    'Logout': 'Abmelden',
    'Admin Dashboard': 'Admin-Oberfläche',
    'Today\'s Celebrants Widget': 'Geburtstags-Aktivitäten',
    'OS Operational Branches': 'Aktive Standorte',
    'Add New Operating Branch': 'Neuen Standort anlegen',
    'Ask AI, search patients, audit logs...': 'KI fragen, Patienten heraussuchen...',
    'EMERGENCY': 'NOTFALL',
    'SLA BREACH ACTIVE': 'SLA-ÜBERSCHREITUNG',
    'SYSTEM IN LOCKDOWN': 'SYSTEM-ABRIEGELUNG',
    'Communications': 'Mitteilungen',
    'Clear All': 'Alle löschen',
    'System Nominal': 'Normalbetrieb',
    'Profile Options': 'Profiloptionen',
    'System Prefs': 'Ausrüstungsverwaltung',
    'Log Out': 'System verlassen',
    'Hospital Details': 'Klinikparameter',
    'Admin': 'Administrator',
    'Today\'s Clinical Events': 'Heutige klinische Termine',
    'Active Patients': 'Aktive Patienten',
    'Doctors Engaged': 'Im Dienst befindlich',
    'Scheduled Consults': 'Gebuchte Termine',
    'Pending Lab Assays': 'Laborproben offen',
    'Total Revenue': 'Gesamtumsatz',
    'System Active Broadcasts': 'Gesendete Ansagen',
    'Language Selected': 'Sprache umgestellt',
    'Enter Branch...': 'STANDORT EINGEBEN...',
    'Add': 'Anlegen',
    'Active Admissions': 'Belegte Betten',
    'Today\'s Clinical Special Events': 'Heutige Sonderereignisse',
    'Action Required': 'Aktion erforderlich',
    'Configure System-wide details': 'Systemweite Details',
    'Registered Personnel': 'Registrierte Kräfte',
    'Quick Access': 'Direktzugriff',
    'Hospital HQ': 'Hauptsitz'
  },
  JA: {
    'Dashboard': 'ダッシュボード',
    'Doctors': '医師管理',
    'Patients': '患者管理',
    'Appointments': '予約管理',
    'Lab Reports': '検査結果',
    'Pharmacy': '処方・調剤',
    'Billing': '会計・請求',
    'Staff & HR': '職員・人事',
    'Inventory': '在庫・備品',
    'Ambulance': '救急車搬送',
    'Communication': '通信・チャット',
    'Birthday System': '記念日通知',
    'Reports': '統計・報告',
    'AI Assistant': 'AIアシスタント',
    'Notifications': 'システム通知',
    'Roles & Permissions': '役割と権限',
    'Settings': '環境設定',
    'Profile': 'プロフィール',
    'Logout': 'ログアウト',
    'Admin Dashboard': '管理者ポータル',
    'Today\'s Celebrants Widget': '本日の祝辞対象者',
    'OS Operational Branches': '稼働中運営拠点',
    'Add New Operating Branch': '新規拠点を登録',
    'Ask AI, search patients, audit logs...': 'AIに問い合わせ、患者検索...',
    'EMERGENCY': '緊急事態発生',
    'SLA BREACH ACTIVE': 'SLA違反警報稼働',
    'SYSTEM IN LOCKDOWN': '回線遮断ロック中',
    'Communications': '通信フィード',
    'Clear All': '全削除',
    'System Nominal': '正常動作中',
    'Profile Options': 'メニュー',
    'System Prefs': 'オプション調整',
    'Log Out': 'ログアウト',
    'Hospital Details': '院内構成情報',
    'Admin': 'システム役員',
    'Today\'s Clinical Events': '院内イベントフィード',
    'Active Patients': '入院・在院患者',
    'Doctors Engaged': '稼働スタッフ数',
    'Scheduled Consults': '診断予約状況',
    'Pending Lab Assays': '検査判定待ち',
    'Total Revenue': '本日売上計',
    'System Active Broadcasts': '緊急告知配信',
    'Language Selected': '言語設定を変更しました',
    'Enter Branch...': '拠点名を入力...',
    'Add': '追加',
    'Active Admissions': '稼働中ベッド',
    'Today\'s Clinical Special Events': '本日の主要出来事',
    'Action Required': '即時確認',
    'Configure System-wide details': 'システム設定の編集',
    'Registered Personnel': '登録従事者',
    'Quick Access': 'クイックアクセス',
    'Hospital HQ': '本部'
  },
  ZH: {
    'Dashboard': '信息控制台',
    'Doctors': '医生名册',
    'Patients': '患者档案',
    'Appointments': '诊疗预约',
    'Lab Reports': '化验检测',
    'Pharmacy': '药品房',
    'Billing': '财务结算',
    'Staff & HR': '人事资源',
    'Inventory': '仓库物资',
    'Ambulance': '救护调度',
    'Communication': '系统通信',
    'Birthday System': '关怀祝福',
    'Reports': '数据分析',
    'AI Assistant': 'AI智能助手',
    'Notifications': '系统公告',
    'Roles & Permissions': '角色与细权',
    'Settings': '系统设定',
    'Profile': '个人信息',
    'Logout': '安全登出',
    'Admin Dashboard': '管理员主页',
    'Today\'s Celebrants Widget': '今日寿星关怀列表',
    'OS Operational Branches': '分院管理',
    'Add New Operating Branch': '开辟新运营网点',
    'Ask AI, search patients, audit logs...': '询问人工智能，搜索病例，审计...',
    'EMERGENCY': '紧急应急',
    'SLA BREACH ACTIVE': 'SLA服务响应超时',
    'SYSTEM IN LOCKDOWN': '系统闭锁保全中',
    'Communications': '即时通信消息',
    'Clear All': '全部清除',
    'System Nominal': '各项指标正常',
    'Profile Options': '配置详情',
    'System Prefs': '系统核心参数',
    'Log Out': '安全退出',
    'Hospital Details': '医院详细状况',
    'Admin': '平台系统管理员',
    'Today\'s Clinical Events': '今日临床重要动态',
    'Active Patients': '当前在院患者',
    'Doctors Engaged': '当值名医统计',
    'Scheduled Consults': '今日排班门诊',
    'Pending Lab Assays': '待审核检验单',
    'Total Revenue': '平台累计营收',
    'System Active Broadcasts': '活动全员群发',
    'Language Selected': '系统语言成功更新',
    'Enter Branch...': '输入新网点分理名...',
    'Add': '确立添加',
    'Active Admissions': '今日入住病例',
    'Today\'s Clinical Special Events': '今日特殊临床荣誉',
    'Action Required': '待办警报响应',
    'Configure System-wide details': '调控医院整体结构',
    'Registered Personnel': '注册在案职工',
    'Quick Access': '快速导航',
    'Hospital HQ': '总医院'
  },
  RU: {
    'Dashboard': 'Инфопанель',
    'Doctors': 'Врачи',
    'Patients': 'Пациенты',
    'Appointments': 'Приемы',
    'Lab Reports': 'Анализы',
    'Pharmacy': 'Аптека',
    'Billing': 'Счета',
    'Staff & HR': 'Кадры и HR',
    'Inventory': 'Складской учет',
    'Ambulance': 'Скорая помощь',
    'Communication': 'Связь',
    'Birthday System': 'Поздравления',
    'Reports': 'Аналитика',
    'AI Assistant': 'ИИ-Помощник',
    'Notifications': 'События',
    'Roles & Permissions': 'Права доступа',
    'Settings': 'Параметры',
    'Profile': 'Профиль',
    'Logout': 'Выход из системы',
    'Admin Dashboard': 'Панель администратора',
    'Today\'s Celebrants Widget': 'Именинники сегодня',
    'OS Operational Branches': 'Действующие филиалы',
    'Add New Operating Branch': 'Зарегистрировать филиал',
    'Ask AI, search patients, audit logs...': 'Поиск ИИ, медицинские карты...',
    'EMERGENCY': 'ТРЕВОГА',
    'SLA BREACH ACTIVE': 'НАРУШЕНИЕ SLA АКТИВНО',
    'SYSTEM IN LOCKDOWN': 'СИСТЕМА ЗАБЛОКИРОВАНА',
    'Communications': 'Центр уведомлений',
    'Clear All': 'Очистить всё',
    'System Nominal': 'Система в норме',
    'Profile Options': 'Настройки аккаунта',
    'System Prefs': 'Системные опции',
    'Log Out': 'Выйти',
    'Hospital Details': 'Сведения о больнице',
    'Admin': 'Администратор',
    'Today\'s Clinical Events': 'События клиники сегодня',
    'Active Patients': 'Активные пациенты',
    'Doctors Engaged': 'Врачей задействовано',
    'Scheduled Consults': 'Запланировано приемов',
    'Pending Lab Assays': 'Анализов на проверке',
    'Total Revenue': 'Выручка клиники',
    'System Active Broadcasts': 'Активные рассылки',
    'Language Selected': 'Язык интерфейса изменен',
    'Enter Branch...': 'НАЗВАНИЕ ФИЛИАЛА...',
    'Add': 'Добавить',
    'Active Admissions': 'Активная госпитализация',
    'Today\'s Clinical Special Events': 'Сегодняшние торжества',
    'Action Required': 'Требует внимания',
    'Configure System-wide details': 'Глобальная конфигурация',
    'Registered Personnel': 'Зарегистрировано сотрудников',
    'Quick Access': 'Быстрый доступ',
    'Hospital HQ': 'Главный корпус'
  },
  PT: {
    'Dashboard': 'Dashboard',
    'Doctors': 'Médicos',
    'Patients': 'Pacientes',
    'Appointments': 'Consultas',
    'Lab Reports': 'Exames e Laboratório',
    'Pharmacy': 'Farmácia',
    'Billing': 'Faturamento',
    'Staff & HR': 'Equipa e RH',
    'Inventory': 'Inventário',
    'Ambulance': 'Ambulância',
    'Communication': 'Mensagens',
    'Birthday System': 'Aniversários',
    'Reports': 'Relatórios',
    'AI Assistant': 'Assistente de IA',
    'Notifications': 'Notificações',
    'Roles & Permissions': 'Cargos e Acessos',
    'Settings': 'Definições',
    'Profile': 'Perfil',
    'Logout': 'Terminar Sessão',
    'Admin Dashboard': 'Painel do Administrador',
    'Today\'s Celebrants Widget': 'Aniversariantes de Hoje',
    'OS Operational Branches': 'Filiais em Operação',
    'Add New Operating Branch': 'Nova Unidade de Operação',
    'Ask AI, search patients, audit logs...': 'Pesquisar pacientes, logs com IA...',
    'EMERGENCY': 'EMERGÊNCIA',
    'SLA BREACH ACTIVE': 'VIOLAÇÃO DE SLA ATIVA',
    'SYSTEM IN LOCKDOWN': 'SISTEMA BLOQUEADO',
    'Communications': 'Central de Avisos',
    'Clear All': 'Limpar Tudo',
    'System Nominal': 'Operações Estáveis',
    'Profile Options': 'Configurar Conta',
    'System Prefs': 'Modos de Ingressos',
    'Log Out': 'Encerrar',
    'Hospital Details': 'Estrutura Hospitalar',
    'Admin': 'Suporte Geral',
    'Today\'s Clinical Events': 'Eventos Clínicos de Hoje',
    'Active Patients': 'Pacientes Internados',
    'Doctors Engaged': 'Equipa Ativa',
    'Scheduled Consults': 'Consultas do Dia',
    'Pending Lab Assays': 'Laudos Pendentes',
    'Total Revenue': 'Receita Bruta',
    'System Active Broadcasts': 'Comunicados Ativos',
    'Language Selected': 'Idioma Atualizado',
    'Enter Branch...': 'NOME DA SUCURSAL...',
    'Add': 'Adicionar',
    'Active Admissions': 'Atendimentos Cruciais',
    'Today\'s Clinical Special Events': 'Eventos Especiais',
    'Action Required': 'Ação Exigida',
    'Configure System-wide details': 'Gerenciar Instalações',
    'Registered Personnel': 'Membros em Exercício',
    'Quick Access': 'Links Úteis',
    'Hospital HQ': 'Sede Principal'
  },
  IT: {
    'Dashboard': 'Cruscotto',
    'Doctors': 'Medici',
    'Patients': 'Pazienti',
    'Appointments': 'Appuntamenti',
    'Lab Reports': 'Laboratorio',
    'Pharmacy': 'Farmacia',
    'Billing': 'Fatturazione',
    'Staff & HR': 'Personale e Risorse',
    'Inventory': 'Magazzino',
    'Ambulance': 'Soccorso Ambulanze',
    'Communication': 'Comunicazioni',
    'Birthday System': 'Compleanni',
    'Reports': 'Resoconti',
    'AI Assistant': 'Assistente IA',
    'Notifications': 'Avvisi',
    'Roles & Permissions': 'Ruoli e Permessi',
    'Settings': 'Impostazioni',
    'Profile': 'Mio Profilo',
    'Logout': 'Esci',
    'Admin Dashboard': 'Pannello Amministratore',
    'Today\'s Celebrants Widget': 'Festeggiati di Oggi',
    'OS Operational Branches': 'Sedi Territoriali',
    'Add New Operating Branch': 'Includi Nuova Sede',
    'Ask AI, search patients, audit logs...': 'Chiedi all\'IA, trova reparto...',
    'EMERGENCY': 'EMERGENZA ROSSA',
    'SLA BREACH ACTIVE': 'SLA IN STATO CRITICO',
    'SYSTEM IN LOCKDOWN': 'BLOCCO DI SICUREZZA',
    'Communications': 'Bacheca Avvisi',
    'Clear All': 'Svuota Tutto',
    'System Nominal': 'Stato Regolare',
    'Profile Options': 'Gestisci Identità',
    'System Prefs': 'Servizi di Sistema',
    'Log Out': 'Esci',
    'Hospital Details': 'Anagrafica Struttura',
    'Admin': 'Super User',
    'Today\'s Clinical Events': 'Notizie della Clinica',
    'Active Patients': 'Degenti Correnti',
    'Doctors Engaged': 'Medici Operativi',
    'Scheduled Consults': 'Visite Fissate',
    'Pending Lab Assays': 'Esami in Lavorazione',
    'Total Revenue': 'Fatturato Complessivo',
    'System Active Broadcasts': 'Messaggi Attivi',
    'Language Selected': 'Lingua Selezionata',
    'Enter Branch...': 'NOME DELLA SEDE...',
    'Add': 'Includi',
    'Active Admissions': 'Ricoveri Odierni',
    'Today\'s Clinical Special Events': 'Ricorrenze Cliniche',
    'Action Required': 'Intervento Richiesto',
    'Configure System-wide details': 'Opzioni Clinica Corrente',
    'Registered Personnel': 'Organico Registrato',
    'Quick Access': 'Collegamenti',
    'Hospital HQ': 'Sede Centrale'
  },
  TR: {
    'Dashboard': 'Yönetici Ekranı',
    'Doctors': 'Hekimler',
    'Patients': 'Hastalar',
    'Appointments': 'Randevular',
    'Lab Reports': 'Laboratuvar',
    'Pharmacy': 'Eczane',
    'Billing': 'Faturalandırma',
    'Staff & HR': 'İnsan Kaynakları',
    'Inventory': 'Envanter Deposu',
    'Ambulance': 'Acil Ambulans',
    'Communication': 'İletişim Hattı',
    'Birthday System': 'Doğum Günleri',
    'Reports': 'İşlem Raporları',
    'AI Assistant': 'Yapay Zeka Destek',
    'Notifications': 'Bilgi Akışı',
    'Roles & Permissions': 'Roller & Yetkiler',
    'Settings': 'Genel Ayarlar',
    'Profile': 'Kullanıcı Profili',
    'Logout': 'Oturumu Kapat',
    'Admin Dashboard': 'Yönetici Paneli',
    'Today\'s Celebrants Widget': 'Bugün Kutlama Kartları',
    'OS Operational Branches': 'Aktif Çalışma Sektörleri',
    'Add New Operating Branch': 'Yeni Hizmet Şubesi Ekle',
    'Ask AI, search patients, audit logs...': 'Yapay Zekaya danışın, kayıt arayın...',
    'EMERGENCY': 'ACİL ALARM',
    'SLA BREACH ACTIVE': 'SLA SÜRESİ AŞILDI',
    'SYSTEM IN LOCKDOWN': 'SİSTEM KİLİTLENDİ',
    'Communications': 'Gelen Duyurular',
    'Clear All': 'Tümünü Temizle',
    'System Nominal': 'Sistem Sağlıklı',
    'Profile Options': 'Kullanıcı Ayarları',
    'System Prefs': 'Atyapı Kontrolü',
    'Log Out': 'Çıkış Yap',
    'Hospital Details': 'Hastane Departmanları',
    'Admin': 'Yönetici Mühendis',
    'Today\'s Clinical Events': 'Klinikte Öne Çıkanlar',
    'Active Patients': 'Aktif Yatan Hasta',
    'Doctors Engaged': 'Görevli Hekimler',
    'Scheduled Consults': 'Bugünkü Randevular',
    'Pending Lab Assays': 'Onay Bekleyen Testler',
    'Total Revenue': 'Günlük Toplam Ciro',
    'System Active Broadcasts': 'Uçtan Uca Yayınlar',
    'Language Selected': 'Sistem Dili Değiştirildi',
    'Enter Branch...': 'ŞUBE ADI GİRİNİZ...',
    'Add': 'Ekle',
    'Active Admissions': 'Klinik Takipleri',
    'Today\'s Clinical Special Events': 'Bugünkü Önemli Günler',
    'Action Required': 'Acil Müdahale',
    'Configure System-wide details': 'Departman ve Şube Kontrolleri',
    'Registered Personnel': 'Kayıtlı Çalışan Sayısı',
    'Quick Access': 'Hızlı Erişim',
    'Hospital HQ': 'Genel Merkez'
  }
};

interface LanguageContextProps {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  languages: Language[];
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>(() => {
    return (localStorage.getItem('admin_locale') as LanguageCode) || 'EN';
  });

  const setLanguage = (lang: LanguageCode) => {
    setCurrentLanguageState(lang);
    localStorage.setItem('admin_locale', lang);
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[currentLanguage];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const dataDict = DATA_TRANSLATIONS[currentLanguage];
    if (dataDict && dataDict[key]) {
      return dataDict[key];
    }
    // Fallback if there is a close mapping
    const trimmedKey = key.trim();
    if (langDict && langDict[trimmedKey]) {
      return langDict[trimmedKey];
    }
    if (dataDict && dataDict[trimmedKey]) {
      return dataDict[trimmedKey];
    }
    if (key.includes(" Prescription (Qty x")) {
      const parts = key.split(" Prescription (Qty x");
      const name = parts[0];
      const qtyPart = parts[1];
      const transName = t(name);
      const transPresc = t("Prescription");
      const transQty = t("Qty");
      return `${transName} ${transPresc} (${transQty} x${qtyPart}`;
    }
    if (key.startsWith("Lab Test: ")) {
       const testName = key.replace("Lab Test: ", "");
       return `${t("Lab Test")}: ${t(testName)}`;
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
